name: continuous integration flow

on:
  workflow_call:
    secrets:
      npm-auth-token:
        description: |
          The token needed to authenticate with internal NPM registry.
          This token is supplied by devops and created as a organization secret called NPM_AUTH      
        required: true

jobs:
  ci:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: add npmrc file
        uses: in-cloud/ga-npmrc-file@v1
        id: npmrc
        with:
          npm-auth-token: ${{ secrets.npm-auth-token }}
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://artifactory.topdanmark.local/artifactory/api/npm/npm-virtual
          always-auth: true
      - run: npm ci
        env:
          NPM_CONFIG_USERCONFIG: ${{ steps.npmrc.outputs.NPMRC_PATH }}      
      - run: npm run prettier:check --if-present
      - run: npm run lint --if-present
      - run: npm run build --if-present
      - run: npm run test --if-present