name: deploy cdk stack(s)

on:
  workflow_call:
    inputs:
      github-environment:
        description: |
          A github repository environment (created by prepare script)
          Valid values are staging or production.      
        required: true
        type: string
      aws-region:
        description: |
          The AWS region to use for the deployment.
          This value is part of the file name used when looking up the configuration.
        required: false
        type: string
        default: 'eu-west-1'
      aws-account-id:
        description: |
          The AWS account ID to use for the deployment.
        required: true
        type: string
      aws-account-name:
        description: |
          The AWS account name to use for the deployment.
          This value is part of the file name used when looking up the configuration
        required: true
        type: string
      stacks:
        description: |
          The stacks to deploy. If not specified, all stacks will be deployed.
          Multiple stacks can be specified by separating them with a space.
        required: false
        type: string
        default: '"*"'
      hotswap:
        description: |
          Whether to hotswap the deployment. If true cdk deploy will be called with --hotswap
        required: false
        type: boolean
        default: false
    secrets:
      npm-auth-token:
        description: |
          The token needed to authenticate with internal NPM registry.
          This token is supplied by devops and created as a organization secret called NPM_AUTH      
        required: true

jobs:
  deploy:
    runs-on: [self-hosted, CoreServices, AWS]
    environment:
      name: ${{ inputs.github-environment }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/cs-github-role
          role-session-name: ${{ inputs.aws-account-name }}
          role-duration-seconds: 14400 # 4hrs (Max on cs-github-role)
      - name: add npmrc file
        uses: in-cloud/ga-npmrc-file@v1
        id: npmrc
        with:
          npm-auth-token: ${{ secrets.npm-auth-token }}
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
        env:
          NPM_CONFIG_USERCONFIG: ${{ steps.npmrc.outputs.NPMRC_PATH }}
      - run: npm run build --if-present
      - name: Deploy with hotswap
        if: ${{ inputs.hotswap == true }}
        run: |
          npx cdk deploy ${{ inputs.stacks }} \
          --context config-file=${{ inputs.aws-account-name }}_${{ inputs.aws-region }} \
          --context accountId=${{ inputs.aws-account-id }} \
          --context region=${{ inputs.aws-region }} \
          --context githubEnvironment=${{ inputs.github-environment }} \
          --require-approval never \
          --hotswap
      - name: Deploy without hotswap
        if: ${{ inputs.hotswap == false }}
        run: | 
          npx cdk deploy ${{ inputs.stacks }} \
          --context config-file=${{ inputs.aws-account-name }}_${{ inputs.aws-region }} \
          --context accountId=${{ inputs.aws-account-id }} \
          --context region=${{ inputs.aws-region }} \
          --require-approval never