name: topdanmark revision

on:
  workflow_call:
    secrets:
      artifactory-auth-token:
        description: |
          The token needed to authenticate with internal Artifactory registry.
          This token is supplied by devops and created as a organization secret called ARTIFACTORY_PASSWORD
        required: true

jobs:
  revision:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2    
      - name: Topdanmark revision policy
        uses: in-cloud/ga-revision@v1
        with:
          artifactory-password: ${{ secrets.artifactory-auth-token }} 